# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'SDWebImage', '~> 3.7.3'
pod 'MD5Digest', '~> 1.0.1'
pod 'Base64', '~> 1.1.2'
pod 'AFNetworking', '~> 2.0'
pod 'AutoLayoutTextViews', '~> 1.2.3'
pod 'IQKeyboardManager', '~> 3.3.4'
pod 'JRSwizzle', '~> 1.0'
pod 'EAMTextView', '~> 0.0.3'
pod 'TTTAttributedLabel', '~> 2.0.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'GPUImage', '~> 0.1.7'
pod 'XMLDictionary', '~> 1.4'
pod 'MWPhotoBrowser', '~> 2.1.2'
#pod 'JElasticPullToRefresh', '~> 1.0.3'
pod 'UMengSocial', '~> 4.4'
#pod 'UMengAnalytics', '~> 4.1.0'
pod 'MagicalRecord', '~> 2.3.2'
pod 'OHAttributedLabel', '~> 3.5.5'

target 'UtravellersAPP' do

end

target 'UtravellersAPPTests' do

end

target 'UtravellersAPPUITests' do

end

